// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Aggregate operation
public struct Aggregate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Aggregate GetRootAsAggregate(ByteBuffer _bb) { return GetRootAsAggregate(_bb, new Aggregate()); }
  public static Aggregate GetRootAsAggregate(ByteBuffer _bb, Aggregate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Aggregate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Common options
  public SubLinq.ArrowIr.RelBase? Base { get { int o = __p.__offset(4); return o != 0 ? (SubLinq.ArrowIr.RelBase?)(new SubLinq.ArrowIr.RelBase()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  /// Child relation
  public SubLinq.ArrowIr.Relation? Rel { get { int o = __p.__offset(6); return o != 0 ? (SubLinq.ArrowIr.Relation?)(new SubLinq.ArrowIr.Relation()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  /// Expressions which will be evaluated to produce to
  /// the rows of the aggregate relation's output.
  public SubLinq.ArrowIr.Expression? Measures(int j) { int o = __p.__offset(8); return o != 0 ? (SubLinq.ArrowIr.Expression?)(new SubLinq.ArrowIr.Expression()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MeasuresLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// Keys by which `aggregations` will be grouped.
  ///
  /// The nested list here is to support grouping sets
  /// eg
  ///
  /// SELECT a, b, c, sum(d)
  /// FROM t
  /// GROUP BY
  ///   GROUPING SETS (
  ///     (a, b, c),
  ///     (a, b),
  ///     (a),
  ///     ()
  ///   );
  public SubLinq.ArrowIr.Grouping? Groupings(int j) { int o = __p.__offset(10); return o != 0 ? (SubLinq.ArrowIr.Grouping?)(new SubLinq.ArrowIr.Grouping()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GroupingsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SubLinq.ArrowIr.Aggregate> CreateAggregate(FlatBufferBuilder builder,
      Offset<SubLinq.ArrowIr.RelBase> baseOffset = default(Offset<SubLinq.ArrowIr.RelBase>),
      Offset<SubLinq.ArrowIr.Relation> relOffset = default(Offset<SubLinq.ArrowIr.Relation>),
      VectorOffset measuresOffset = default(VectorOffset),
      VectorOffset groupingsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    Aggregate.AddGroupings(builder, groupingsOffset);
    Aggregate.AddMeasures(builder, measuresOffset);
    Aggregate.AddRel(builder, relOffset);
    Aggregate.AddBase(builder, baseOffset);
    return Aggregate.EndAggregate(builder);
  }

  public static void StartAggregate(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddBase(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.RelBase> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
  public static void AddRel(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Relation> relOffset) { builder.AddOffset(1, relOffset.Value, 0); }
  public static void AddMeasures(FlatBufferBuilder builder, VectorOffset measuresOffset) { builder.AddOffset(2, measuresOffset.Value, 0); }
  public static VectorOffset CreateMeasuresVector(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Expression>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMeasuresVectorBlock(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Expression>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMeasuresVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGroupings(FlatBufferBuilder builder, VectorOffset groupingsOffset) { builder.AddOffset(3, groupingsOffset.Value, 0); }
  public static VectorOffset CreateGroupingsVector(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Grouping>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGroupingsVectorBlock(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Grouping>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGroupingsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SubLinq.ArrowIr.Aggregate> EndAggregate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // base
    builder.Required(o, 6);  // rel
    builder.Required(o, 8);  // measures
    builder.Required(o, 10);  // groupings
    return new Offset<SubLinq.ArrowIr.Aggregate>(o);
  }
};


}
