// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

public enum Bound : byte
{
  NONE = 0,
  Preceding = 1,
  Following = 2,
  CurrentRow = 3,
};


}
