// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// A function call expression
public struct Call : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Call GetRootAsCall(ByteBuffer _bb) { return GetRootAsCall(_bb, new Call()); }
  public static Call GetRootAsCall(ByteBuffer _bb, Call obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Call __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// The function to call
  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  /// The arguments passed to `name`.
  public SubLinq.ArrowIr.Expression? Arguments(int j) { int o = __p.__offset(6); return o != 0 ? (SubLinq.ArrowIr.Expression?)(new SubLinq.ArrowIr.Expression()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ArgumentsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// Possible ordering of input. These are useful
  /// in aggregates where ordering in meaningful such as
  /// string concatenation
  public SubLinq.ArrowIr.SortKey? Orderings(int j) { int o = __p.__offset(8); return o != 0 ? (SubLinq.ArrowIr.SortKey?)(new SubLinq.ArrowIr.SortKey()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OrderingsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SubLinq.ArrowIr.Call> CreateCall(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset argumentsOffset = default(VectorOffset),
      VectorOffset orderingsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    Call.AddOrderings(builder, orderingsOffset);
    Call.AddArguments(builder, argumentsOffset);
    Call.AddName(builder, nameOffset);
    return Call.EndCall(builder);
  }

  public static void StartCall(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddArguments(FlatBufferBuilder builder, VectorOffset argumentsOffset) { builder.AddOffset(1, argumentsOffset.Value, 0); }
  public static VectorOffset CreateArgumentsVector(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Expression>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArgumentsVectorBlock(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Expression>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartArgumentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOrderings(FlatBufferBuilder builder, VectorOffset orderingsOffset) { builder.AddOffset(2, orderingsOffset.Value, 0); }
  public static VectorOffset CreateOrderingsVector(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.SortKey>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOrderingsVectorBlock(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.SortKey>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartOrderingsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SubLinq.ArrowIr.Call> EndCall(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    builder.Required(o, 6);  // arguments
    return new Offset<SubLinq.ArrowIr.Call>(o);
  }
};


}
