// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// A single WHEN x THEN y fragment.
public struct CaseFragment : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static CaseFragment GetRootAsCaseFragment(ByteBuffer _bb) { return GetRootAsCaseFragment(_bb, new CaseFragment()); }
  public static CaseFragment GetRootAsCaseFragment(ByteBuffer _bb, CaseFragment obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CaseFragment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Datalinq.ArrowIr.Expression? Match { get { int o = __p.__offset(4); return o != 0 ? (Datalinq.ArrowIr.Expression?)(new Datalinq.ArrowIr.Expression()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Datalinq.ArrowIr.Expression? Result { get { int o = __p.__offset(6); return o != 0 ? (Datalinq.ArrowIr.Expression?)(new Datalinq.ArrowIr.Expression()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Datalinq.ArrowIr.CaseFragment> CreateCaseFragment(FlatBufferBuilder builder,
      Offset<Datalinq.ArrowIr.Expression> matchOffset = default(Offset<Datalinq.ArrowIr.Expression>),
      Offset<Datalinq.ArrowIr.Expression> resultOffset = default(Offset<Datalinq.ArrowIr.Expression>)) {
    builder.StartTable(2);
    CaseFragment.AddResult(builder, resultOffset);
    CaseFragment.AddMatch(builder, matchOffset);
    return CaseFragment.EndCaseFragment(builder);
  }

  public static void StartCaseFragment(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMatch(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Expression> matchOffset) { builder.AddOffset(0, matchOffset.Value, 0); }
  public static void AddResult(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Expression> resultOffset) { builder.AddOffset(1, resultOffset.Value, 0); }
  public static Offset<Datalinq.ArrowIr.CaseFragment> EndCaseFragment(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // match
    builder.Required(o, 6);  // result
    return new Offset<Datalinq.ArrowIr.CaseFragment>(o);
  }
};


}
