// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

/// A concrete bound, which can be an expression or unbounded
public enum ConcreteBoundImpl : byte
{
  NONE = 0,
  Expression = 1,
  Unbounded = 2,
};


}
