// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Boundary is the current row
public struct CurrentRow : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static CurrentRow GetRootAsCurrentRow(ByteBuffer _bb) { return GetRootAsCurrentRow(_bb, new CurrentRow()); }
  public static CurrentRow GetRootAsCurrentRow(ByteBuffer _bb, CurrentRow obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CurrentRow __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCurrentRow(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SubLinq.ArrowIr.CurrentRow> EndCurrentRow(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.CurrentRow>(o);
  }
};


}
