// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DurationLiteral : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static DurationLiteral GetRootAsDurationLiteral(ByteBuffer _bb) { return GetRootAsDurationLiteral(_bb, new DurationLiteral()); }
  public static DurationLiteral GetRootAsDurationLiteral(ByteBuffer _bb, DurationLiteral obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DurationLiteral __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<SubLinq.ArrowIr.DurationLiteral> CreateDurationLiteral(FlatBufferBuilder builder,
      long value = 0) {
    builder.StartTable(1);
    DurationLiteral.AddValue(builder, value);
    return DurationLiteral.EndDurationLiteral(builder);
  }

  public static void StartDurationLiteral(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, long value) { builder.AddLong(0, value, 0); }
  public static Offset<SubLinq.ArrowIr.DurationLiteral> EndDurationLiteral(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.DurationLiteral>(o);
  }
};


}
