// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

/// A union for the different colum remapping variants
public enum Emit : byte
{
  NONE = 0,
  Remap = 1,
  PassThrough = 2,
};


}
