// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Field name in a relation, in ordinal position of the relation's schema.
public struct FieldIndex : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static FieldIndex GetRootAsFieldIndex(ByteBuffer _bb) { return GetRootAsFieldIndex(_bb, new FieldIndex()); }
  public static FieldIndex GetRootAsFieldIndex(ByteBuffer _bb, FieldIndex obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldIndex __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Position { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<SubLinq.ArrowIr.FieldIndex> CreateFieldIndex(FlatBufferBuilder builder,
      uint position = 0) {
    builder.StartTable(1);
    FieldIndex.AddPosition(builder, position);
    return FieldIndex.EndFieldIndex(builder);
  }

  public static void StartFieldIndex(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPosition(FlatBufferBuilder builder, uint position) { builder.AddUint(0, position, 0); }
  public static Offset<SubLinq.ArrowIr.FieldIndex> EndFieldIndex(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.FieldIndex>(o);
  }
};


}
