// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

/// The kind of window function to be executed
public enum Frame : byte
{
  Rows = 0,
  Range = 1,
};


}
