// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Int8Literal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Int8Literal GetRootAsInt8Literal(ByteBuffer _bb) { return GetRootAsInt8Literal(_bb, new Int8Literal()); }
  public static Int8Literal GetRootAsInt8Literal(ByteBuffer _bb, Int8Literal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Int8Literal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }

  public static Offset<SubLinq.ArrowIr.Int8Literal> CreateInt8Literal(FlatBufferBuilder builder,
      sbyte value = 0) {
    builder.StartTable(1);
    Int8Literal.AddValue(builder, value);
    return Int8Literal.EndInt8Literal(builder);
  }

  public static void StartInt8Literal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, sbyte value) { builder.AddSbyte(0, value, 0); }
  public static Offset<SubLinq.ArrowIr.Int8Literal> EndInt8Literal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.Int8Literal>(o);
  }
};


}
