// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

public enum IntervalLiteralImpl : byte
{
  NONE = 0,
  IntervalLiteralMonths = 1,
  IntervalLiteralDaysMilliseconds = 2,
};


}
