// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct KeyValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static KeyValue GetRootAsKeyValue(ByteBuffer _bb) { return GetRootAsKeyValue(_bb, new KeyValue()); }
  public static KeyValue GetRootAsKeyValue(ByteBuffer _bb, KeyValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public KeyValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Datalinq.ArrowIr.Literal? Key { get { int o = __p.__offset(4); return o != 0 ? (Datalinq.ArrowIr.Literal?)(new Datalinq.ArrowIr.Literal()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Datalinq.ArrowIr.Literal? Value { get { int o = __p.__offset(6); return o != 0 ? (Datalinq.ArrowIr.Literal?)(new Datalinq.ArrowIr.Literal()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Datalinq.ArrowIr.KeyValue> CreateKeyValue(FlatBufferBuilder builder,
      Offset<Datalinq.ArrowIr.Literal> keyOffset = default(Offset<Datalinq.ArrowIr.Literal>),
      Offset<Datalinq.ArrowIr.Literal> valueOffset = default(Offset<Datalinq.ArrowIr.Literal>)) {
    builder.StartTable(2);
    KeyValue.AddValue(builder, valueOffset);
    KeyValue.AddKey(builder, keyOffset);
    return KeyValue.EndKeyValue(builder);
  }

  public static void StartKeyValue(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal> keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal> valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<Datalinq.ArrowIr.KeyValue> EndKeyValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // key
    builder.Required(o, 6);  // value
    return new Offset<Datalinq.ArrowIr.KeyValue>(o);
  }
};


}
