// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// A single column of literal values.
public struct LiteralColumn : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static LiteralColumn GetRootAsLiteralColumn(ByteBuffer _bb) { return GetRootAsLiteralColumn(_bb, new LiteralColumn()); }
  public static LiteralColumn GetRootAsLiteralColumn(ByteBuffer _bb, LiteralColumn obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LiteralColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// The literal values of the column
  public Datalinq.ArrowIr.Literal? Elements(int j) { int o = __p.__offset(4); return o != 0 ? (Datalinq.ArrowIr.Literal?)(new Datalinq.ArrowIr.Literal()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ElementsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Datalinq.ArrowIr.LiteralColumn> CreateLiteralColumn(FlatBufferBuilder builder,
      VectorOffset elementsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    LiteralColumn.AddElements(builder, elementsOffset);
    return LiteralColumn.EndLiteralColumn(builder);
  }

  public static void StartLiteralColumn(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddElements(FlatBufferBuilder builder, VectorOffset elementsOffset) { builder.AddOffset(0, elementsOffset.Value, 0); }
  public static VectorOffset CreateElementsVector(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateElementsVectorBlock(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartElementsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Datalinq.ArrowIr.LiteralColumn> EndLiteralColumn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // elements
    return new Offset<Datalinq.ArrowIr.LiteralColumn>(o);
  }
};


}
