// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Literal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Literal GetRootAsLiteral(ByteBuffer _bb) { return GetRootAsLiteral(_bb, new Literal()); }
  public static Literal GetRootAsLiteral(ByteBuffer _bb, Literal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Literal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Datalinq.ArrowIr.LiteralImpl ImplType { get { int o = __p.__offset(4); return o != 0 ? (Datalinq.ArrowIr.LiteralImpl)__p.bb.Get(o + __p.bb_pos) : Datalinq.ArrowIr.LiteralImpl.NONE; } }
  /// Literal value data; for null literals do not include this field.
  public TTable? Impl<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Datalinq.ArrowIr.BooleanLiteral ImplAsBooleanLiteral() { return Impl<Datalinq.ArrowIr.BooleanLiteral>().Value; }
  public Datalinq.ArrowIr.Int8Literal ImplAsInt8Literal() { return Impl<Datalinq.ArrowIr.Int8Literal>().Value; }
  public Datalinq.ArrowIr.Int16Literal ImplAsInt16Literal() { return Impl<Datalinq.ArrowIr.Int16Literal>().Value; }
  public Datalinq.ArrowIr.Int32Literal ImplAsInt32Literal() { return Impl<Datalinq.ArrowIr.Int32Literal>().Value; }
  public Datalinq.ArrowIr.Int64Literal ImplAsInt64Literal() { return Impl<Datalinq.ArrowIr.Int64Literal>().Value; }
  public Datalinq.ArrowIr.UInt8Literal ImplAsUInt8Literal() { return Impl<Datalinq.ArrowIr.UInt8Literal>().Value; }
  public Datalinq.ArrowIr.UInt16Literal ImplAsUInt16Literal() { return Impl<Datalinq.ArrowIr.UInt16Literal>().Value; }
  public Datalinq.ArrowIr.UInt32Literal ImplAsUInt32Literal() { return Impl<Datalinq.ArrowIr.UInt32Literal>().Value; }
  public Datalinq.ArrowIr.UInt64Literal ImplAsUInt64Literal() { return Impl<Datalinq.ArrowIr.UInt64Literal>().Value; }
  public Datalinq.ArrowIr.DateLiteral ImplAsDateLiteral() { return Impl<Datalinq.ArrowIr.DateLiteral>().Value; }
  public Datalinq.ArrowIr.TimeLiteral ImplAsTimeLiteral() { return Impl<Datalinq.ArrowIr.TimeLiteral>().Value; }
  public Datalinq.ArrowIr.TimestampLiteral ImplAsTimestampLiteral() { return Impl<Datalinq.ArrowIr.TimestampLiteral>().Value; }
  public Datalinq.ArrowIr.IntervalLiteral ImplAsIntervalLiteral() { return Impl<Datalinq.ArrowIr.IntervalLiteral>().Value; }
  public Datalinq.ArrowIr.DurationLiteral ImplAsDurationLiteral() { return Impl<Datalinq.ArrowIr.DurationLiteral>().Value; }
  public Datalinq.ArrowIr.DecimalLiteral ImplAsDecimalLiteral() { return Impl<Datalinq.ArrowIr.DecimalLiteral>().Value; }
  public Datalinq.ArrowIr.Float16Literal ImplAsFloat16Literal() { return Impl<Datalinq.ArrowIr.Float16Literal>().Value; }
  public Datalinq.ArrowIr.Float32Literal ImplAsFloat32Literal() { return Impl<Datalinq.ArrowIr.Float32Literal>().Value; }
  public Datalinq.ArrowIr.Float64Literal ImplAsFloat64Literal() { return Impl<Datalinq.ArrowIr.Float64Literal>().Value; }
  public Datalinq.ArrowIr.ListLiteral ImplAsListLiteral() { return Impl<Datalinq.ArrowIr.ListLiteral>().Value; }
  public Datalinq.ArrowIr.StructLiteral ImplAsStructLiteral() { return Impl<Datalinq.ArrowIr.StructLiteral>().Value; }
  public Datalinq.ArrowIr.MapLiteral ImplAsMapLiteral() { return Impl<Datalinq.ArrowIr.MapLiteral>().Value; }
  public Datalinq.ArrowIr.StringLiteral ImplAsStringLiteral() { return Impl<Datalinq.ArrowIr.StringLiteral>().Value; }
  public Datalinq.ArrowIr.BinaryLiteral ImplAsBinaryLiteral() { return Impl<Datalinq.ArrowIr.BinaryLiteral>().Value; }
  public Datalinq.ArrowIr.FixedSizeBinaryLiteral ImplAsFixedSizeBinaryLiteral() { return Impl<Datalinq.ArrowIr.FixedSizeBinaryLiteral>().Value; }
  /// Type of the literal value. This must match `impl`.
  public Datalinq.ArrowIr.Arrow.Field? Type { get { int o = __p.__offset(8); return o != 0 ? (Datalinq.ArrowIr.Arrow.Field?)(new Datalinq.ArrowIr.Arrow.Field()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Datalinq.ArrowIr.Literal> CreateLiteral(FlatBufferBuilder builder,
      Datalinq.ArrowIr.LiteralImpl impl_type = Datalinq.ArrowIr.LiteralImpl.NONE,
      int implOffset = 0,
      Offset<Datalinq.ArrowIr.Arrow.Field> typeOffset = default(Offset<Datalinq.ArrowIr.Arrow.Field>)) {
    builder.StartTable(3);
    Literal.AddType(builder, typeOffset);
    Literal.AddImpl(builder, implOffset);
    Literal.AddImplType(builder, impl_type);
    return Literal.EndLiteral(builder);
  }

  public static void StartLiteral(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddImplType(FlatBufferBuilder builder, Datalinq.ArrowIr.LiteralImpl implType) { builder.AddByte(0, (byte)implType, 0); }
  public static void AddImpl(FlatBufferBuilder builder, int implOffset) { builder.AddOffset(1, implOffset, 0); }
  public static void AddType(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Arrow.Field> typeOffset) { builder.AddOffset(2, typeOffset.Value, 0); }
  public static Offset<Datalinq.ArrowIr.Literal> EndLiteral(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 8);  // type
    return new Offset<Datalinq.ArrowIr.Literal>(o);
  }
  public static void FinishLiteralBuffer(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedLiteralBuffer(FlatBufferBuilder builder, Offset<Datalinq.ArrowIr.Literal> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
