// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

/// The varieties of relations
public enum RelationImpl : byte
{
  NONE = 0,
  Aggregate = 1,
  Filter = 2,
  Join = 3,
  Limit = 4,
  LiteralRelation = 5,
  OrderBy = 6,
  Project = 7,
  SetOperation = 8,
  Source = 9,
};


}
