// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

/// The kind of set operation being performed.
public enum SetOpKind : byte
{
  Union = 0,
  Intersection = 1,
  Difference = 2,
};


}
