// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// A set operation on two or more relations
public struct SetOperation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SetOperation GetRootAsSetOperation(ByteBuffer _bb) { return GetRootAsSetOperation(_bb, new SetOperation()); }
  public static SetOperation GetRootAsSetOperation(ByteBuffer _bb, SetOperation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetOperation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Common options
  public SubLinq.ArrowIr.RelBase? Base { get { int o = __p.__offset(4); return o != 0 ? (SubLinq.ArrowIr.RelBase?)(new SubLinq.ArrowIr.RelBase()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  /// Child relations
  public SubLinq.ArrowIr.Relation? Rels(int j) { int o = __p.__offset(6); return o != 0 ? (SubLinq.ArrowIr.Relation?)(new SubLinq.ArrowIr.Relation()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RelsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// The kind of set operation
  public SubLinq.ArrowIr.SetOpKind SetOp { get { int o = __p.__offset(8); return o != 0 ? (SubLinq.ArrowIr.SetOpKind)__p.bb.Get(o + __p.bb_pos) : SubLinq.ArrowIr.SetOpKind.Union; } }

  public static Offset<SubLinq.ArrowIr.SetOperation> CreateSetOperation(FlatBufferBuilder builder,
      Offset<SubLinq.ArrowIr.RelBase> baseOffset = default(Offset<SubLinq.ArrowIr.RelBase>),
      VectorOffset relsOffset = default(VectorOffset),
      SubLinq.ArrowIr.SetOpKind set_op = SubLinq.ArrowIr.SetOpKind.Union) {
    builder.StartTable(3);
    SetOperation.AddRels(builder, relsOffset);
    SetOperation.AddBase(builder, baseOffset);
    SetOperation.AddSetOp(builder, set_op);
    return SetOperation.EndSetOperation(builder);
  }

  public static void StartSetOperation(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddBase(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.RelBase> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
  public static void AddRels(FlatBufferBuilder builder, VectorOffset relsOffset) { builder.AddOffset(1, relsOffset.Value, 0); }
  public static VectorOffset CreateRelsVector(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Relation>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRelsVectorBlock(FlatBufferBuilder builder, Offset<SubLinq.ArrowIr.Relation>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSetOp(FlatBufferBuilder builder, SubLinq.ArrowIr.SetOpKind setOp) { builder.AddByte(2, (byte)setOp, 0); }
  public static Offset<SubLinq.ArrowIr.SetOperation> EndSetOperation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // base
    builder.Required(o, 6);  // rels
    return new Offset<SubLinq.ArrowIr.SetOperation>(o);
  }
};


}
