// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Struct field access
public struct StructField : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static StructField GetRootAsStructField(ByteBuffer _bb) { return GetRootAsStructField(_bb, new StructField()); }
  public static StructField GetRootAsStructField(ByteBuffer _bb, StructField obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StructField __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// The position of the field in the struct schema
  public uint Position { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<SubLinq.ArrowIr.StructField> CreateStructField(FlatBufferBuilder builder,
      uint position = 0) {
    builder.StartTable(1);
    StructField.AddPosition(builder, position);
    return StructField.EndStructField(builder);
  }

  public static void StartStructField(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPosition(FlatBufferBuilder builder, uint position) { builder.AddUint(0, position, 0); }
  public static Offset<SubLinq.ArrowIr.StructField> EndStructField(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.StructField>(o);
  }
};


}
