// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UInt16Literal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static UInt16Literal GetRootAsUInt16Literal(ByteBuffer _bb) { return GetRootAsUInt16Literal(_bb, new UInt16Literal()); }
  public static UInt16Literal GetRootAsUInt16Literal(ByteBuffer _bb, UInt16Literal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UInt16Literal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<SubLinq.ArrowIr.UInt16Literal> CreateUInt16Literal(FlatBufferBuilder builder,
      ushort value = 0) {
    builder.StartTable(1);
    UInt16Literal.AddValue(builder, value);
    return UInt16Literal.EndUInt16Literal(builder);
  }

  public static void StartUInt16Literal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, ushort value) { builder.AddUshort(0, value, 0); }
  public static Offset<SubLinq.ArrowIr.UInt16Literal> EndUInt16Literal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.UInt16Literal>(o);
  }
};


}
