// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UInt64Literal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static UInt64Literal GetRootAsUInt64Literal(ByteBuffer _bb) { return GetRootAsUInt64Literal(_bb, new UInt64Literal()); }
  public static UInt64Literal GetRootAsUInt64Literal(ByteBuffer _bb, UInt64Literal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UInt64Literal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<Datalinq.ArrowIr.UInt64Literal> CreateUInt64Literal(FlatBufferBuilder builder,
      ulong value = 0) {
    builder.StartTable(1);
    UInt64Literal.AddValue(builder, value);
    return UInt64Literal.EndUInt64Literal(builder);
  }

  public static void StartUInt64Literal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, ulong value) { builder.AddUlong(0, value, 0); }
  public static Offset<Datalinq.ArrowIr.UInt64Literal> EndUInt64Literal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Datalinq.ArrowIr.UInt64Literal>(o);
  }
};


}
