// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// An unbounded window bound
public struct Unbounded : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Unbounded GetRootAsUnbounded(ByteBuffer _bb) { return GetRootAsUnbounded(_bb, new Unbounded()); }
  public static Unbounded GetRootAsUnbounded(ByteBuffer _bb, Unbounded obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Unbounded __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartUnbounded(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SubLinq.ArrowIr.Unbounded> EndUnbounded(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.Unbounded>(o);
  }
};


}
