// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr.Arrow
{

public enum DateUnit : short
{
  DAY = 0,
  MILLISECOND = 1,
};


}
