// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Datalinq.ArrowIr.Arrow
{

/// ----------------------------------------------------------------------
/// Endianness of the platform producing the data
public enum Endianness : short
{
  Little = 0,
  Big = 1,
};


}
