// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr.Arrow
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FloatingPoint : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static FloatingPoint GetRootAsFloatingPoint(ByteBuffer _bb) { return GetRootAsFloatingPoint(_bb, new FloatingPoint()); }
  public static FloatingPoint GetRootAsFloatingPoint(ByteBuffer _bb, FloatingPoint obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FloatingPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SubLinq.ArrowIr.Arrow.Precision Precision { get { int o = __p.__offset(4); return o != 0 ? (SubLinq.ArrowIr.Arrow.Precision)__p.bb.GetShort(o + __p.bb_pos) : SubLinq.ArrowIr.Arrow.Precision.HALF; } }

  public static Offset<SubLinq.ArrowIr.Arrow.FloatingPoint> CreateFloatingPoint(FlatBufferBuilder builder,
      SubLinq.ArrowIr.Arrow.Precision precision = SubLinq.ArrowIr.Arrow.Precision.HALF) {
    builder.StartTable(1);
    FloatingPoint.AddPrecision(builder, precision);
    return FloatingPoint.EndFloatingPoint(builder);
  }

  public static void StartFloatingPoint(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPrecision(FlatBufferBuilder builder, SubLinq.ArrowIr.Arrow.Precision precision) { builder.AddShort(0, (short)precision, 0); }
  public static Offset<SubLinq.ArrowIr.Arrow.FloatingPoint> EndFloatingPoint(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubLinq.ArrowIr.Arrow.FloatingPoint>(o);
  }
};


}
