// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SubLinq.ArrowIr.Arrow
{

public enum UnionMode : short
{
  Sparse = 0,
  Dense = 1,
};


}
